name: "Test"
on:
  pull_request:
  push:
jobs:
  build-2105:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-21.05.tar.gz"
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v20
    - run: nix-build test.nix
  build-unstable:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz"
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v20
    - run: nix-build test.nix
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: '.'
        extensions: 'h,c'
