name: "Test"
on:
  pull_request:
  push:
jobs:
  build-2003:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-20.03.tar.gz"
    steps:
    - uses: actions/checkout@v3.0.1
    - uses: cachix/install-nix-action@v12
    - run: nix-build test.nix
  build-2009:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-20.09.tar.gz"
    steps:
    - uses: actions/checkout@v3.0.1
    - uses: cachix/install-nix-action@v12
    - run: nix-build test.nix
  build-unstable:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz"
    steps:
    - uses: actions/checkout@v3.0.1
    - uses: cachix/install-nix-action@v12
    - run: nix-build test.nix
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,c'
